version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db-directory:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'monapp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
volumes:
  mysql-data:
