version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: monapp
    ports:
      - "3306:3306"
    volumes:
      - ./init-db-directory/init.sql:/docker-entrypoint-initdb.d/init-db.sql
      # - mysql-data:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  jenkins:
    build: ./Jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "5000:5000"
# volumes:
#   mysql-data:
  
